HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = r0236198321_ft1.fit \
			  test_events.root

HD_REFDATA_SUBDIR       = fermi/pointlike

include ${HD_STD_MAKEFILE}
