HD_COMPONENT_NAME       = glast

HD_COMPONENT_VERS       =

HD_INSTALL_REFDATA      = LivetimeCubeTemplate

HD_REFDATA_SUBDIR       = fermi/skymaps

HD_TEST_REFDATA		= aeff_P6_v1_diff_front.fits

include ${HD_STD_MAKEFILE}
